name: "CD: Deployement"

on:
    push:
        branches: [ main ]
    workflow_dispatch:

jobs:
    coding_style:
        name: "ğŸŒ Epitech coding-style"
        uses: ./.github/workflows/coding-style.yml

    project-compilation:
        name: "âš™ï¸ Project compilation"
        uses: ./.github/workflows/compilation.yml

    project-tests:
        name: "âœ… Tests"
        uses: ./.github/workflows/tests.yml
        needs: [ project-compilation ]

    repository_mirroring:
        name: "ğŸš€ Repository mirroring"
        runs-on: ubuntu-latest
        needs: [ coding_style, project-tests]

        steps:
        - name: "ğŸ“¥ Checkout repository"
          uses: actions/checkout@v3
          with:
            fetch-depth: 0
        
        - name: "ğŸš€ Epitech mirroring"
          uses: pixta-dev/repository-mirroring-action@v1
          with:
            target_repo_url: ${{ secrets.DEPLOYMENT_URL }}
            ssh_private_key: ${{ secrets.DEPLOYEMENT_SSH_KEY }}
