name: "âœ… CI: Tests"

on:
    pull_request:
    workflow_dispatch:
    workflow_call:

jobs:
    project_tests:
        name: "âœ… Project tests"
        runs-on: ubuntu-latest
        container:
            image: epitechcontent/epitest-docker:latest
        continue-on-error: false
        timeout-minutes: 3

        strategy:
            matrix:
                type: ['tests_criterion', 'ftest', 'tests_custom']

        steps:
        - name: "ğŸ“¥ Checkout repository"
          uses: actions/checkout@v3

        - name: "âš™ï¸ Run ${{ matrix.type }}"
          run: make ${{ matrix.type }}

    project_coverage:
        name: "ğŸ“‹ Project coverage"
        runs-on: ubuntu-latest
        container:
            image: epitechcontent/epitest-docker:latest
        needs: [ project_tests ]
        timeout-minutes: 3
        
        steps:
        - name: "ğŸ“¥ Checkout repository"
          uses: actions/checkout@v3
        
        - name: "âš™ï¸ Run tests with Epitech rule"
          run: make tests_custom
        
        - name: "âš™ï¸ Run lines coverage"
          id: lines_coverage
          run: |
            echo 'lines_coverage<<EOF' >> $GITHUB_OUTPUT
            make coverage >> $GITHUB_OUTPUT
            echo 'EOF' >> $GITHUB_OUTPUT

        - name: "âš™ï¸ Run branch coverage"
          id: branch_coverage
          run: |
            echo 'branch_coverage<<EOF' >> $GITHUB_OUTPUT
            make coverage_branch >> $GITHUB_OUTPUT
            echo 'EOF' >> $GITHUB_OUTPUT

        - name: "ğŸ’¬ Display coverage"
          uses: thollander/actions-comment-pull-request@v2
          with:
            message: |
                # ğŸ“‹ Coverage report @${{ github.event.pull_request.assignee.login }}
                ## Lines coverage
                ${{ steps.lines_coverage.outputs.lines_coverage }}
                ## Branch coverage
                ${{ steps.branch_coverage.outputs.branch_coverage }}
